(** Generates [command-panel.md], the demo vault's control panel.

    Spec: {!page-"feature-command-block"}.  The note is generated rather than
    written by hand for one reason: it claims to list {e every} command the
    server understands, and a hand-written list stops being true the moment
    {!Lsp_lib.Command_block.command} grows a constructor.  Here the catalogue
    and the block both come from [all_of_command], so adding a command updates
    the demo vault on the next build.

    The output is promoted into the source tree — see [../dune] — because the
    vault is meant to be opened in an editor, not built. *)

open Core
module Command_block = Lsp_lib.Command_block

let catalogue_table () =
  "| Line | Does |\n|---|---|\n"
  ^ (List.map Command_block.all_of_command ~f:(fun c ->
       sprintf
         "| `%s` | %s |"
         (Command_block.name_of_command c)
         (Command_block.doc_of_command c))
     |> String.concat ~sep:"\n")
;;

let () =
  print_string
    (String.concat
       [ {|<!-- GENERATED by pkg/oystermark/lsp/demo-vault/tools/gen_panel.ml — do not edit.
     Regenerate with: dune build @demo-vault. -->

# Command panel

Every line below is a command the server understands. Each one gets a **code
lens** above it (click it), a **code action** when the cursor is on it, and
**completion** inside the fence — put the cursor on a blank line in the block
and ask for completions to see the catalogue.

|}
       ; Command_block.render Command_block.all_of_command
       ; {|Two of them are missing a clickable lens here, and that is the feature
working: `daily/prev` and `daily/next` are answered *relative to the note the
block sits in*, and this note is not a daily note. Their lenses say so instead
of disappearing. Open [[2026-07-26]] to see the same two lines come alive.

## The catalogue

|}
       ; catalogue_table ()
       ; {|

This table and the block above are both generated from
`Lsp_lib.Command_block.all_of_command`, so they cannot drift from what the
server actually accepts.

## Try breaking it

An unrecognized line is a diagnostic, not silence — see [[diagnostics]].

## Try writing one

Open a note with no block at all — [[anchors]] — and ask for code actions
anywhere in it: *Insert oysterlsp command block*. It writes only the commands
that can run in that note.
|}
       ])
;;
