root := justfile_directory() / "../../.."

default:
    @just --list --justfile {{ justfile() }}

# Rebuild the binary.
build:
    cd {{ root }} && dune build pkg/oystermark/lsp/main.exe

install: build
    cd {{ root }} && dune install oystermark --sections=bin
    @echo "installed: $(command -v oystermark-lsp)"
    @ls -l "$(command -v oystermark-lsp)"
